languages = {
    'ru': {
        'send_phone': 'Отправить номер',
        'skip_phone': 'Продолжить без номера',
        'greeting': 'Здравствуйте! Чтобы начать, выберите один из вариантов ниже:\n• отправить номер (необязательно)\n• открыть меню',
        'send_phone_request': 'Если хотите, отправьте свой номер телефона с помощью кнопки ниже.',
        'thanks_for_phone': 'Отлично! Теперь вы можете пользоваться ботом.\nОткройте меню',
        'menu': 'Меню',
        'menu_activate': 'Рады видеть тебя у нас в боте <b><a href="https://showgo.uz">ShowGo</a></b> - билетного помощника №1 в Ташкенте! \n\nВыберите нужны раздел по кнопкам ниже:',
        'menu_activate_by_button': '🛠️ <b>Что-то непонятно?</b> Нажмите «Техподдержка» — и мы поможем!\n\n📢 <b>Хотите узнать о нас больше?</b> Подписывайтесь на наши соцсети и следите за новостями!',        
        'menu_tip': '📌 Нажмите кнопку "Меню", чтобы вернуться сюда в любой момент.',
        'tickets': 'Билеты',
        'support': 'Техподдержка',
        'language_change': 'Сменить язык',
        'language_change_activate': '🌍 Пожалуйста, выберите язык',
        'language_set': '✅ Язык успешно изменён!',
        'user_not_found': 'Вы не авторизованы. Пожалуйста, отправьте команду /start для авторизации.',
        'error_occurred': 'Произошла ошибка. Пожалуйста, попробуйте снова.',
        'wrong_contact': 'Пожалуйста, отправьте контакт, используя кнопку ниже, и убедитесь, что это ваш контакт.',
        'send_contact_please': 'Пожалуйста, отправьте контакт, используя кнопку ниже.',
        'not_exist_category': 'Нет доступных категорий вопросов.',
        'not_exist_answer': 'Нет доступных ответов на данный вопрос.',
        'what_is_your_question': '❓ Выберите вопрос, который вас интересует',
        'what_is_your_answer_cat': '📂 Выберите категорию вашего вопроса',
        'connect_operator': 'Соединиться с оператором',
        'waiting_operator': 'Ожидание оператора...',
        'operator_found': 'Оператор найден! Вас подключает',
        'operator_not_available': 'К сожалению, все операторы заняты. Вы добавлены в очередь ожидания. Оператор свяжется с вами как можно скорее.',
        'rate_operator': 'Пожалуйста, оцените работу оператора (нажмите на звезду):',
        'chat_closed': 'Чат закрыт.',
        'operator_closed_chat': 'Оператор закрыл чат.',
        'chat_message': 'Сообщение в чате',
        'operator_name': 'Оператор',
        'rating': 'Рейтинг',
        'stars': 'Помощь была полезной?',
        'helpful': '👍 Да, спасибо!',
        'not_helpful': '👎 Нет, нужен оператор',
        'is_this_helpful': 'Это было полезно?',
        'active_chat_exists': 'У вас уже есть активный чат',
        'please_finish_current_chat': 'Пожалуйста, завершите текущий разговор перед подключением к новому оператору.',
        'operator_found_success': 'Оператор найден!',
        'operator_rating': 'Рейтинг:',
        'waiting_operator_message': 'Ожидайте первого сообщения оператора...',
        'all_operators_busy': 'Все операторы заняты',
        'request_in_queue': 'Ваш запрос добавлен в очередь. Оператор свяжется с вами в ближайшее время.',
        'try_later': 'Если вам нужна срочная помощь, попробуйте позже.',
        'friend': 'друг',
        'welcome': 'Добро пожаловать',
        'social': 'Мы в соцсетях',
        'give_social': '🌐 Наши социальные сети',
        'lang_russian': '🇷🇺 Русский',
        'lang_english': '🇬🇧 English',
        'lang_kyrgyz': '🇺🇿 O‘zbekcha',  # Это название остаётся без изменений, но теперь оно не используется
    },
    'en': {
        'send_phone': 'Send phone number',
        'skip_phone': 'Continue without number',
        'greeting': 'Hello! To get started, choose one of the options below:\n• send your phone number (optional)\n• open the menu',
        'send_phone_request': 'If you want, send your phone number using the button below.',
        'thanks_for_phone': 'Great! Now you can use the bot.\nOpen the menu',
        'menu': 'Menu',
        'menu_activate': 'We are glad to see you in our bot <b><a href="https://showgo.uz">ShowGo</a></b> - the #1 ticket assistant in Tashkent! \n\nChoose the needed section by the buttons below:',
        'menu_activate_by_button': 'Something not clear? Click on "Support" and we will help!\nWant to know more about us? Click on "We in social networks" and follow all the news!',
        'menu_tip': '📌 Tap the "Menu" button anytime to return here.',
        'tickets': 'Tickets',
        'support': 'Support',
        'language_change': 'Change language',
        'language_change_activate': '🌍 Please select a language',
        'language_set': '✅ Language successfully changed!',
        'user_not_found': 'You are not authorized. Please send the /start command to authorize.',
        'error_occurred': 'An error occurred. Please try again.',
        'wrong_contact': 'Please send the contact using the button below and make sure it is your contact.',
        'send_contact_please': 'Please send the contact using the button below.',
        'not_exist_category': 'No available question categories.',
        'not_exist_answer': 'No available answers for this question.',
        'what_is_your_question': '❓ Please select the question you are interested in',
        'what_is_your_answer_cat': '📂 Please select the category of your question',
        'connect_operator': 'Connect with operator',
        'waiting_operator': 'Waiting for operator...',
        'operator_found': 'Operator found! Connecting you...',
        'operator_not_available': 'Unfortunately, all operators are busy. You have been added to the waiting queue. An operator will contact you as soon as possible.',
        'rate_operator': 'Please rate the operator (click on the star):',
        'chat_closed': 'Chat closed.',
        'operator_closed_chat': 'Operator closed the chat.',
        'chat_message': 'Chat message',
        'operator_name': 'Operator',
        'rating': 'Rating',
        'stars': 'Was the help useful?',
        'helpful': '👍 Yes, thank you!',
        'not_helpful': '👎 No, I need an operator',
        'is_this_helpful': 'Was this helpful?',
        'active_chat_exists': 'You already have an active chat',
        'please_finish_current_chat': 'Please finish your current conversation before connecting to a new operator.',
        'operator_found_success': 'Operator found!',
        'operator_rating': 'Rating:',
        'waiting_operator_message': 'Waiting for the operator\'s first message...',
        'all_operators_busy': 'All operators are busy',
        'request_in_queue': 'Your request has been added to the queue. An operator will contact you shortly.',
        'try_later': 'If you need urgent help, please try again later.',
        'friend': 'friend',
        'welcome': 'Welcome',
        'social': 'Follow us on social media',
        'give_social': '🌐 Our Social Media',
        'lang_russian': '🇷🇺 Русский',
        'lang_english': '🇬🇧 English',
        'lang_kyrgyz': '🇺🇿 O‘zbekcha',   # остаётся без изменений
    },
    'ky': {  # ключ остался ky, но теперь это узбекский язык
        'send_phone': 'Telefon raqamini yuborish',
        'skip_phone': 'Raqamsiz davom etish',
        'greeting': 'Assalomu alaykum! Boshlash uchun quyidagi variantlardan birini tanlang:\n• telefon raqamini yuborish (majburiy emas)\n• menyuni ochish',
        'send_phone_request': 'Agar istasangiz, telefon raqamingizni quyidagi tugma orqali yuboring.',
        'thanks_for_phone': 'Zo‘r! Endi botdan foydalanishingiz mumkin.\nMenyuni oching',
        'menu': 'Menyu',
        'menu_activate': '🎉 <b>Asosiy menyu</b>\n\nQuyidagi tugmalardan birini tanlang:',
        'menu_activate_by_button': 'Nimadir tushunarsizmi? "Texnik yordam" tugmasini bosing, biz yordam beramiz!\nBiz haqimizda ko‘proq bilishni istaysizmi? "Ijtimoiy tarmoqlarda biz" tugmasini bosing va barcha yangiliklarni kuzatib boring!',
        'menu_tip': '📌 Istalgan vaqtda shu menyuga qaytish uchun "Menyu" tugmasini bosing.',
        'tickets': 'Chiptalar',
        'support': 'Texnik yordam',
        'language_change': 'Tilni o‘zgartirish',
        'language_change_activate': '🌍 Iltimos, tilni tanlang',
        'language_set': '✅ Til muvaffaqiyatli o‘zgartirildi!',
        'user_not_found': 'Siz avtorizatsiyadan o‘tmagansiz. Avtorizatsiyadan o‘tish uchun /start buyrug‘ini yuboring.',
        'error_occurred': 'Xatolik yuz berdi. Iltimos, qayta urinib ko‘ring.',
        'wrong_contact': 'Iltimos, quyidagi tugma orqali kontaktni yuboring va bu sizning kontaktingiz ekanligiga ishonch hosil qiling.',
        'send_contact_please': 'Iltimos, quyidagi tugma orqali kontaktni yuboring.',
        'not_exist_category': 'Mavjud savol kategoriyalari yo‘q.',
        'not_exist_answer': 'Bu savolga mavjud javoblar yo‘q.',
        'what_is_your_question': '❓ Sizni qiziqtirgan savolni tanlang',
        'what_is_your_answer_cat': '📂 Savolingiz qaysi kategoriyaga tegishli?',
        'connect_operator': 'Operator bilan bog‘lanish',
        'waiting_operator': 'Operator kutilmoqda...',
        'operator_found': 'Operator topildi! Sizni ulamoqda...',
        'operator_not_available': 'Afsuski, barcha operatorlar band. Siz navbatga qo‘shildingiz. Operator imkon qadar tezroq siz bilan bog‘lanadi.',
        'rate_operator': 'Iltimos, operator ishini baholang (yulduzchani bosing):',
        'chat_closed': 'Chat yopildi.',
        'operator_closed_chat': 'Operator chatni yopdi.',
        'chat_message': 'Chatdagi xabar',
        'operator_name': 'Operator',
        'rating': 'Reyting',
        'stars': 'Yordam foydali bo‘ldimi?',
        'helpful': '👍 Ha, rahmat!',
        'not_helpful': '👎 Yo‘q, operator kerak',
        'is_this_helpful': 'Bu foydali bo‘ldimi?',
        'active_chat_exists': 'Sizda allaqachon faol chat mavjud',
        'please_finish_current_chat': 'Yangi operatorga ulanishdan oldin, joriy suhbatni tugating.',
        'operator_found_success': 'Operator topildi!',
        'operator_rating': 'Reyting:',
        'waiting_operator_message': 'Operatorning birinchi xabarini kuting...',
        'all_operators_busy': 'Barcha operatorlar band',
        'request_in_queue': 'So‘rovingiz navbatga qo‘shildi. Operator yaqin orada siz bilan bog‘lanadi.',
        'try_later': 'Shoshilinch yordam kerak bo‘lsa, keyinroq urinib ko‘ring.',
        'friend': 'do‘st',
        'welcome': 'Xush kelibsiz',
        'social': 'Ijtimoiy tarmoqlarda biz',
        'give_social': '🌐 Ijtimoiy tarmoqlar',
        'lang_russian': '🇷🇺 Русский',
        'lang_english': '🇬🇧 English',
        'lang_kyrgyz': '🇺🇿 O‘zbekcha', 
    }
}
