languages = {
    'ru': {
        'send_phone': 'Отправить номер',
        'greeting': 'Здравствуйте! Для полного доступа, пожалуйста, отправьте номер телефона по кнопке ниже.',
        'send_phone_request': 'Отправьте свой номер телефона, используя кнопку ниже.',
        'thanks_for_phone': 'Спасибо! Теперь вы можете пользоваться ботом.\nОткройте меню',
        'menu': 'Меню',
        'menu_activate': 'Вы открыли меню. Ниже список доступных команд:\nТехподдержка - связаться с поддержкой\nЯзык - смена языка',
        'tickets': 'Билеты',
        'support': 'Техподдержка',
        'language_change': 'Язык',
        'language_change_activate': 'Выберите язык',
        'language_set': 'Язык успешно изменён',
        'user_not_found': 'Вы не авторизованы. Пожалуйста, отправьте команду /start для авторизации.',
        'error_occurred': 'Произошла ошибка. Пожалуйста, попробуйте снова.',
        'wrong_contact': 'Пожалуйста, отправьте контакт, используя кнопку ниже, и убедитесь, что это ваш контакт.',
        'send_contact_please': 'Пожалуйста, отправьте контакт, используя кнопку ниже.',
        'not_exist_category': 'Нет доступных категорий вопросов.',
        'not_exist_answer': 'Нет доступных ответов на данный вопрос.',
        'what_is_your_question': 'Какой у вас вопрос?',
        'what_is_your_answer_cat': 'К чему относится ваш вопрос?',
        'connect_operator': 'Соединиться с оператором',
        'waiting_operator': 'Ожидание оператора...',
        'operator_found': 'Оператор найден! Вас подключает',
        'operator_not_available': 'К сожалению, все операторы заняты. Вы добавлены в очередь ожидания. Оператор свяжется с вами как можно скорее.',
        'rate_operator': 'Пожалуйста, оцените работу оператора (нажмите на звезду):',
        'chat_closed': 'Чат закрыт.',
        'operator_closed_chat': 'Оператор закрыл чат.',
        'chat_message': 'Сообщение в чате',
        'operator_name': 'Оператор',
        'rating': 'Рейтинг',
        'stars': 'Помощь была полезной?',
        'helpful': '👍 Да, спасибо!',
        'not_helpful': '👎 Нет, нужен оператор',
        'is_this_helpful': 'Это было полезно?',
        'active_chat_exists': 'У вас уже есть активный чат',
        'please_finish_current_chat': 'Пожалуйста, завершите текущий разговор перед подключением к новому оператору.',
        'operator_found_success': 'Оператор найден!',
        'operator_rating': 'Рейтинг:',
        'waiting_operator_message': 'Ожидайте первого сообщения оператора...',
        'all_operators_busy': 'Все операторы заняты',
        'request_in_queue': 'Ваш запрос добавлен в очередь. Оператор свяжется с вами в ближайшее время.',
        'try_later': 'Если вам нужна срочная помощь, попробуйте позже.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'O‘zbekcha',  # Это название остаётся без изменений, но теперь оно не используется
    },
    'en': {
        'send_phone': 'Send phone number',
        'greeting': 'Hello! For full access, please send your phone number using the button below.',
        'send_phone_request': 'Please send your phone number using the button below.',
        'thanks_for_phone': 'Thank you! Now you can use the bot.\nOpen the menu',
        'menu': 'Menu',
        'menu_activate': 'You have opened the menu. Below is a list of available commands:\nSupport - contact support\nLanguage - change language',
        'tickets': 'Tickets',
        'support': 'Support',
        'language_change': 'Language',
        'language_change_activate': 'Select language',
        'language_set': 'Language successfully changed',
        'user_not_found': 'You are not authorized. Please send the /start command to authorize.',
        'error_occurred': 'An error occurred. Please try again.',
        'wrong_contact': 'Please send the contact using the button below and make sure it is your contact.',
        'send_contact_please': 'Please send the contact using the button below.',
        'not_exist_category': 'No available question categories.',
        'not_exist_answer': 'No available answers for this question.',
        'what_is_your_question': 'What is your question?',
        'what_is_your_answer_cat': 'What category does your question belong to?',
        'connect_operator': 'Connect with operator',
        'waiting_operator': 'Waiting for operator...',
        'operator_found': 'Operator found! Connecting you...',
        'operator_not_available': 'Unfortunately, all operators are busy. You have been added to the waiting queue. An operator will contact you as soon as possible.',
        'rate_operator': 'Please rate the operator (click on the star):',
        'chat_closed': 'Chat closed.',
        'operator_closed_chat': 'Operator closed the chat.',
        'chat_message': 'Chat message',
        'operator_name': 'Operator',
        'rating': 'Rating',
        'stars': 'Was the help useful?',
        'helpful': '👍 Yes, thank you!',
        'not_helpful': '👎 No, I need an operator',
        'is_this_helpful': 'Was this helpful?',
        'active_chat_exists': 'You already have an active chat',
        'please_finish_current_chat': 'Please finish your current conversation before connecting to a new operator.',
        'operator_found_success': 'Operator found!',
        'operator_rating': 'Rating:',
        'waiting_operator_message': 'Waiting for the operator\'s first message...',
        'all_operators_busy': 'All operators are busy',
        'request_in_queue': 'Your request has been added to the queue. An operator will contact you shortly.',
        'try_later': 'If you need urgent help, please try again later.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'O‘zbekcha',   # остаётся без изменений
    },
    'ky': {  # ключ остался ky, но теперь это узбекский язык
        'send_phone': 'Telefon raqamini yuborish',
        'greeting': 'Assalomu alaykum! To‘liq kirish uchun, iltimos, quyidagi tugma orqali telefon raqamingizni yuboring.',
        'send_phone_request': 'Iltimos, quyidagi tugma orqali telefon raqamingizni yuboring.',
        'thanks_for_phone': 'Rahmat! Endi botdan foydalanishingiz mumkin.\nMenyuni oching',
        'menu': 'Menyu',
        'menu_activate': 'Siz menyuni ochdingiz. Quyida mavjud buyruqlar ro‘yxati:\nTexnik yordam - yordam xizmati bilan bog‘lanish\nTil - tilni o‘zgartirish',
        'tickets': 'Chiptalar',
        'support': 'Texnik yordam',
        'language_change': 'Til',
        'language_change_activate': 'Tilni tanlang',
        'language_set': 'Til muvaffaqiyatli o‘zgartirildi',
        'user_not_found': 'Siz avtorizatsiyadan o‘tmagansiz. Avtorizatsiyadan o‘tish uchun /start buyrug‘ini yuboring.',
        'error_occurred': 'Xatolik yuz berdi. Iltimos, qayta urinib ko‘ring.',
        'wrong_contact': 'Iltimos, quyidagi tugma orqali kontaktni yuboring va bu sizning kontaktingiz ekanligiga ishonch hosil qiling.',
        'send_contact_please': 'Iltimos, quyidagi tugma orqali kontaktni yuboring.',
        'not_exist_category': 'Mavjud savol kategoriyalari yo‘q.',
        'not_exist_answer': 'Bu savolga mavjud javoblar yo‘q.',
        'what_is_your_question': 'Savolingiz qanday?',
        'what_is_your_answer_cat': 'Savolingiz qaysi kategoriyaga tegishli?',
        'connect_operator': 'Operator bilan bog‘lanish',
        'waiting_operator': 'Operator kutilmoqda...',
        'operator_found': 'Operator topildi! Sizni ulamoqda...',
        'operator_not_available': 'Afsuski, barcha operatorlar band. Siz navbatga qo‘shildingiz. Operator imkon qadar tezroq siz bilan bog‘lanadi.',
        'rate_operator': 'Iltimos, operator ishini baholang (yulduzchani bosing):',
        'chat_closed': 'Chat yopildi.',
        'operator_closed_chat': 'Operator chatni yopdi.',
        'chat_message': 'Chatdagi xabar',
        'operator_name': 'Operator',
        'rating': 'Reyting',
        'stars': 'Yordam foydali bo‘ldimi?',
        'helpful': '👍 Ha, rahmat!',
        'not_helpful': '👎 Yo‘q, operator kerak',
        'is_this_helpful': 'Bu foydali bo‘ldimi?',
        'active_chat_exists': 'Sizda allaqachon faol chat mavjud',
        'please_finish_current_chat': 'Yangi operatorga ulanishdan oldin, joriy suhbatni tugating.',
        'operator_found_success': 'Operator topildi!',
        'operator_rating': 'Reyting:',
        'waiting_operator_message': 'Operatorning birinchi xabarini kuting...',
        'all_operators_busy': 'Barcha operatorlar band',
        'request_in_queue': 'So‘rovingiz navbatga qo‘shildi. Operator yaqin orada siz bilan bog‘lanadi.',
        'try_later': 'Shoshilinch yordam kerak bo‘lsa, keyinroq urinib ko‘ring.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'O‘zbekcha',  
    }
}
