languages = {
    'ru': {
        'send_phone': 'Отправить номер',
        'greeting': 'Здравствуйте! Для полного доступа, пожалуйста, отправьте номер телефона по кнопке ниже.',
        'send_phone_request': 'Отправьте свой номер телефона, используя кнопку ниже.',
        'thanks_for_phone': 'Спасибо! Теперь вы можете пользоваться ботом.\nОткройте меню',
        'menu': 'Меню',
        'menu_activate': 'Вы открыли меню. Ниже список доступных команд:\nТехподдержка - связаться с поддержкой\nЯзык - смена языка',
        'tickets': 'Билеты',
        'support': 'Техподдержка',
        'language_change': 'Язык',
        'language_change_activate': 'Выберите язык',
        'language_set': 'Язык успешно изменён',
        'user_not_found': 'Вы не авторизованы. Пожалуйста, отправьте команду /start для авторизации.',
        'error_occurred': 'Произошла ошибка. Пожалуйста, попробуйте снова.',
        'wrong_contact': 'Пожалуйста, отправьте контакт, используя кнопку ниже, и убедитесь, что это ваш контакт.',
        'send_contact_please': 'Пожалуйста, отправьте контакт, используя кнопку ниже.',
        'not_exist_category': 'Нет доступных категорий вопросов.',
        'not_exist_answer': 'Нет доступных ответов на данный вопрос.',
        'what_is_your_question': 'Какой у вас вопрос?',
        'what_is_your_answer_cat': 'К чему относится ваш вопрос?',
        'connect_operator': 'Соединиться с оператором',
        'waiting_operator': 'Ожидание оператора...',
        'operator_found': 'Оператор найден! Вас подключает',
        'operator_not_available': 'К сожалению, все операторы заняты. Вы добавлены в очередь ожидания. Оператор свяжется с вами как можно скорее.',
        'rate_operator': 'Пожалуйста, оцените работу оператора (нажмите на звезду):',
        'chat_closed': 'Чат закрыт.',
        'operator_closed_chat': 'Оператор закрыл чат.',
        'chat_message': 'Сообщение в чате',
        'operator_name': 'Оператор',
        'rating': 'Рейтинг',
        'stars': 'Помощь была полезной?',
        'helpful': '👍 Да, спасибо!',
        'not_helpful': '👎 Нет, нужен оператор',
        'is_this_helpful': 'Это было полезно?',
        'active_chat_exists': 'У вас уже есть активный чат',
        'please_finish_current_chat': 'Пожалуйста, завершите текущий разговор перед подключением к новому оператору.',
        'operator_found_success': 'Оператор найден!',
        'operator_rating': 'Рейтинг:',
        'waiting_operator_message': 'Ожидайте первого сообщения оператора...',
        'all_operators_busy': 'Все операторы заняты',
        'request_in_queue': 'Ваш запрос добавлен в очередь. Оператор свяжется с вами в ближайшее время.',
        'try_later': 'Если вам нужна срочная помощь, попробуйте позже.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'Кыргызча',
    },
    'en': {
        'send_phone': 'Send phone number',
        'greeting': 'Hello! For full access, please send your phone number using the button below.',
        'send_phone_request': 'Please send your phone number using the button below.',
        'thanks_for_phone': 'Thank you! Now you can use the bot.\nOpen the menu',
        'menu': 'Menu',
        'menu_activate': 'You have opened the menu. Below is a list of available commands:\nSupport - contact support\nLanguage - change language',
        'tickets': 'Tickets',
        'support': 'Support',
        'language_change': 'Language',
        'language_change_activate': 'Select language',
        'language_set': 'Language successfully changed',
        'user_not_found': 'You are not authorized. Please send the /start command to authorize.',
        'error_occurred': 'An error occurred. Please try again.',
        'wrong_contact': 'Please send the contact using the button below and make sure it is your contact.',
        'send_contact_please': 'Please send the contact using the button below.',
        'not_exist_category': 'No available question categories.',
        'not_exist_answer': 'No available answers for this question.',
        'what_is_your_question': 'What is your question?',
        'what_is_your_answer_cat': 'What category does your question belong to?',
        'connect_operator': 'Connect with operator',
        'waiting_operator': 'Waiting for operator...',
        'operator_found': 'Operator found! Connecting you...',
        'operator_not_available': 'Unfortunately, all operators are busy. You have been added to the waiting queue. An operator will contact you as soon as possible.',
        'rate_operator': 'Please rate the operator (click on the star):',
        'chat_closed': 'Chat closed.',
        'operator_closed_chat': 'Operator closed the chat.',
        'chat_message': 'Chat message',
        'operator_name': 'Operator',
        'rating': 'Rating',
        'stars': 'Was the help useful?',
        'helpful': '👍 Yes, thank you!',
        'not_helpful': '👎 No, I need an operator',
        'is_this_helpful': 'Was this helpful?',
        'active_chat_exists': 'You already have an active chat',
        'please_finish_current_chat': 'Please finish your current conversation before connecting to a new operator.',
        'operator_found_success': 'Operator found!',
        'operator_rating': 'Rating:',
        'waiting_operator_message': 'Waiting for the operator\'s first message...',
        'all_operators_busy': 'All operators are busy',
        'request_in_queue': 'Your request has been added to the queue. An operator will contact you shortly.',
        'try_later': 'If you need urgent help, please try again later.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'Кыргызча',
    },
    'ky': {
        'send_phone': 'Телефон номерин жибер',
        'greeting': 'Саламатсызбы! Толук кирүү үчүн телефон номерин төмөнкү батырмачка басып жибериңиз.',
        'send_phone_request': 'Телефон номерин төмөнкү батырмачка басып жибериңиз.',
        'thanks_for_phone': 'Рахмат! Эми сиз ботту колдоно аласыз.\nМенюну ачыңыз',
        'menu': 'Меню',
        'menu_activate': 'Сиз менюну ачтыңыз. Төмөндө бар командалардын тизмеси:\nТехподдержка - колдоо кызматына байланыш\nЯзык - тилди өзгөртүү',
        'tickets': 'Билеттер',
        'support': 'Техподдержка',
        'language_change': 'Язык',
        'language_change_activate': 'Тилди тандаңыз',
        'language_set': 'Тил ийгиликтүү өзгөртүлдү',
        'user_not_found': 'Сиз авторизацияланбадыңыз. Авторизация үчүн /start командасын жибериңиз.',
        'error_occurred': 'Ката кетти. Кайра аракет кылыңыз.',
        'wrong_contact': 'Төмөнкү батырма аркылуу контактты жиберип, анын сизге тиешелүү экенин текшериңиз.',
        'send_contact_please': 'Төмөнкү батырма аркылуу контактты жибериңиз.',
        'not_exist_category': 'Суроолордун жеткиликтүү категориялары жок.',
        'not_exist_answer': 'Бул суроого жеткиликтүү жооптар жок.',
        'what_is_your_question': 'Сурооңуз кандай?',
        'what_is_your_answer_cat': 'Сурооңуз кайсы категорияга тиешелүү?',
        'connect_operator': 'Оператор менен байланышуу',
        'waiting_operator': 'Оператор күтүлүүдө...',
        'operator_found': 'Оператор табылды! Сизди туташтырып жатат...',
        'operator_not_available': 'Өкүнчүлүй, бардык операторлор занятуу. Сиз күтүүнүн кезегине кошулдыңыз. Оператор мүмкүн болушунча тез байланыш чыгат.',
        'rate_operator': 'Оператордун иш-аракетин баалаңыз (жылдызга басыңыз):',
        'chat_closed': 'Чат жабылды.',
        'operator_closed_chat': 'Оператор чатты жабды.',
        'chat_message': 'Чаттагы билдирүү',
        'operator_name': 'Оператор',
        'rating': 'Рейтинг',
        'stars': 'Жардам пайдалуу болду?',
        'helpful': '👍 Ооба, рахмат!',
        'not_helpful': '👎 Жок, операторго керек',
        'is_this_helpful': 'Бул пайдалуу болду?',
        'active_chat_exists': 'Сизде уже активдүү чат бар',
        'please_finish_current_chat': 'Жаңы оператор менен байланышка чыгуудан мурун өзүңүздүн учурдагы сүйлөшүүнү аяктаңыз.',
        'operator_found_success': 'Оператор табылды!',
        'operator_rating': 'Рейтинг:',
        'waiting_operator_message': 'Операторун биринчи билдирүүсүнүн күтүлүүсүндө...',
        'all_operators_busy': 'Бардык операторлор занятуу',
        'request_in_queue': 'Сиздин суроолору кезегине кошулды. Оператор жакын арада сизге байланыш чыгат.',
        'try_later': 'Ыкмалуу жардам керек болсо, кейин аракет кылыңыз.',
        'lang_russian': 'Русский',
        'lang_english': 'English',
        'lang_kyrgyz': 'Кыргызча',
    }
}