"""Added lang column for users

Revision ID: 3bcd3c2d08ad
Revises: 0e5dc44e7167
Create Date: 2026-02-11 17:31:18.597200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcd3c2d08ad'
down_revision: Union[str, Sequence[str], None] = '0e5dc44e7167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.Enum('RU', 'EN', 'KY', name='languageenum', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
