"""made answers to Text type

Revision ID: 63f10c94bf8f
Revises: f80cce9ba60f
Create Date: 2026-03-10 17:43:11.673017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f10c94bf8f'
down_revision: Union[str, Sequence[str], None] = 'f80cce9ba60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'answer_ru',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
    op.alter_column('answers', 'answer_en',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
    op.alter_column('answers', 'answer_ky',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'answer_ky',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('answers', 'answer_en',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('answers', 'answer_ru',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
