"""created answers for help

Revision ID: ae6acd0eacc5
Revises: b47135ce74d9
Create Date: 2026-02-12 18:48:17.809321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae6acd0eacc5'
down_revision: Union[str, Sequence[str], None] = 'b47135ce74d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('name_ky', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('question_ru', sa.String(length=255), nullable=False),
    sa.Column('question_en', sa.String(length=255), nullable=False),
    sa.Column('question_ky', sa.String(length=255), nullable=False),
    sa.Column('answer_ru', sa.String(length=255), nullable=False),
    sa.Column('answer_en', sa.String(length=255), nullable=False),
    sa.Column('answer_ky', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['answer_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table('answers')
    op.drop_table('answer_categories')
    # ### end Alembic commands ###
